### ISSUE TITLE
Friendly name to the MAC address

### ISSUE THREAD

**Issue by SmartM-ui** [shogunxam/ESP32_BLETracker#32]
Hi,
would it be possible to associate a friendly name for each NUT that does not correspond to the real name and have it displayed next to the MAC ADDRESS in the devices?
It would be convenient to be able to immediately identify the NUT without having to remember the MAC, especially for new devices.

For example:
CXXXXXXXXXX0 with real name nut> friendly name Rocco
FXXXXXXXXXX3 with real name nut> friendly name Moana
DXXXXXXXXXX3 with real name nut> friendly name Selen

It's possible?

Thanks in advance

**Comment by shogunxam** [comment]
Hi @SmartM-ui,
possible is possible I have to study how to structure the interface.

**Comment by SmartM-ui** [comment]
Thanks for your work, I'm sure you will succeed!
