### ISSUE TITLE
MAX_NON_ADV_PERIOD in control panel

### ISSUE THREAD

**Issue by SmartM-ui** [shogunxam/ESP32_BLETracker#33]
Dear Mario,
would you be able to insert in the control panel the possibility of managing the MAX_NON_ADV_PERIOD in order to better define any false outputs when the NUT fails to communicate with the ESP for a few minutes?
You could put it in configuration, near the scan interval
Thanks in advance

**Comment by shogunxam** [comment]
Hi @SmartM-ui this is feasible.

**Comment by SmartM-ui** [comment]
Thanks!

**Comment by SmartM-ui** [comment]
Great Mario!
It works very well
