### ISSUE TITLE
Wrong time reported in the logs

### ISSUE THREAD

**Issue by shogunxam** [shogunxam/ESP32_BLETracker#36]
As described here https://github.com/espressif/arduino-esp32/issues/3797 there is an issue with the DST set in the NTP Time library .
The issue can be fixed using the proper Time Zone name instead of GMT and DST offsets.
Here there is the list of all the available [Time Zones](https://github.com/nayarsystems/posix_tz_db/blob/master/zones.csv)

Time Zone format is:
GMTGMT-1, M3.4.0/1,M10.4.0/2 
* GMTGMT-1 is the name of the time zone  
* GMT-1 is the abbreviation used when DST is off  1 hour is the time difference from GMT  
* GMT is the abbreviation used when DST is on  
* ,M3 is the third month 
*  .4 is the forth occurrence of the day in the month when DST starts 
*  .0 is Sunday 
*  /1 is the time in hours when DST starts 
* ,M10 is the tenth month  
* .4 is the forth occurrence of the day in the month when DST ends 
*  .0 is Sunday 
* /2 is the time in hours when DST ends

**Comment by SmartM-ui** [comment]
Great news,
I had noticed the time discrepancy between events in Home Assistant and BLEtracker.

Thanks Mario!

**Comment by SmartM-ui** [comment]
Hi,
in the latest development version I'm testing, the date and time are correct.
Thank you
