### ISSUE TITLE
the scanning of the smartphones with bluetooth

### ISSUE THREAD

**Issue by DivanX10** [shogunxam/ESP32_BLETracker#4]
Thank you for your hard work. Excellent firmware. Tell me, could you add bluetooth scanning? For example, in the option enable scanning of phones that only have bluetooth.

**Comment by shogunxam** [comment]
Hi, I have to investigate the feasibility, If I remember correctly ESP32 can operate in BLE or in Bluetooth classic mode but not at same time

**Comment by DivanX10** [comment]
Yes, ESP32 can work in both classic mode and BLE. If you only need to scan smartphones with bluetooth, you can simply comment out BLE and uncomment bluetooth, or choose whether to use BLE or bluetooth when uploading a sketch. If it is possible of course.
