### ISSUE TITLE
Report the date and time of the last battery level detection

### ISSUE THREAD

**Issue by SmartM-ui** [shogunxam/ESP32_BLETracker#40]
Would it be possible to report the date and time of the last battery level reading?
It would be useful in case one carries out the detection in manual mode.
It would also be advisable to provide for the retain of the data in case of ESP shutdown.

Thanks in advance

**Comment by shogunxam** [comment]
I have added the last battery reading date and time into System Information web page

**Comment by SmartM-ui** [comment]
Thanks BIG Mario!
