### ISSUE TITLE
Build problem

### ISSUE THREAD

**Issue by SadE54** [shogunxam/ESP32_BLETracker#56]
Hi , I'm trying to build the master branch using platform.io: but I get this : 
------------Tool Manager: Installing git+https://github.com/espressif/arduino-esp32#9be784f69b696d5bbb189a2fe5f1750ce2855426
git version 2.30.0.windows.2
Cloning into 'C:\Users\******\.platformio\.cache\tmp\pkg-installing-bjh9ohhm'...
remote: Enumerating objects: 30622, done.
remote: Counting objects: 100% (152/152), done.
remote: Compressing objects: 100% (77/77), done.
Receiving objects: 100% (30622, reused 150 (delta 62), pack-reused 30470Receiving objects: 100% (30622/30622), 1.12 GiB | 21.12 MiB/s     
/30622), 1.13 GiB | 22.65 MiB/s, done.
Resolving deltas: 100% (18749/18749), done.
Updating files: 100% (6908/6908), done.
fatal: not a git repository: ../../.git/modules/libraries/AzureIoT
fatal: could not reset submodule index
Error: VCS: Could not process command ['git', 'reset', '--hard', '9be784f69b696d5bbb189a2fe5f1750ce2855426']

I guess there's some dependencies problem, but I cannot figured it out 😫

**Comment by shogunxam** [comment]
Hi @SadE54 , sorry for the late reply.
It seems an issue related to the expressif repository. I check and I let you know

**Comment by shogunxam** [comment]
I tried on Linux and Windows and it worked like a charm.
In my Windows 10 VM I installed from scratch Visual Studio Code, PlatformIo and git (all latest versions) and I have downloaded the latest released zip of the project (the same of the master branch).
Try to close VSCode, rename/delete the .platform folder in your user folder and delete the .pio folder created by PlatformIo inside the project root.
Be sure to have enough free storage on your disk (4Gb should be enough).
Start VSCode and open the project folder.
Wait until PlatformIo ends all its jobs, it could ask to restart VSCode, do it. 
Wait until PlatformIo ends the indexing (you can see it at bottom in the status bar), it could take some time.
Now you should be able to build the project.
Let me know if you have the same error also after you followed all the steps

**Comment by ozett** [comment]
can you provide a general-binary to flash it on my test-device?
would appreciate this...

**Comment by shogunxam** [comment]
Hi @ozett currently is not possible because some configurations such as WiFi name and WiFi password are hard-coded in the user_config.h file and they cannot set at runtime.

**Comment by ozett** [comment]
uhhh. 

that's really unfortunate (for Me). 
can't you steal a gui for those two things from the other esp32 projects on github?
:-))

**Comment by shogunxam** [comment]
I have to study how to make a peer to peer connection between the esp32 and i.e a mobile phone.
Unfortunately I haven't much time to dedicate to the project in these days, but it could be one of the next improvements.
Anyway should not be too difficult build and flash the project using PlatformIo
