### ISSUE TITLE
v3.7b UTF-8 issues: Broker won't accept messages 

### ISSUE THREAD

**Issue by l33tn00b** [shogunxam/ESP32_BLETracker#70]
I'm running the latest release (v3.7b) of the tracker against mosquitto 2.0.11-1.
Mosquitto will error out with "Bad socket read/write on client <unknown>: Malformed UTF-8" when receiving messages from the tracker. 
(Frankly, I have no clue why this happens. I'm also running v3.5 against another mosquitto instance and everything is fine.)
Edit: Seems like a(n overly) long ID (which will be used to generate the topic) is the likely cuplrit. Shortened the ID to five characters, all lowercase, voilà: Broker will accept the messages. For the sake ov clarity: the ID I had used previously was made of ten mixed upper-/lowercase characters (no digits, no special characters, plain roman characters only).

**Comment by shogunxam** [comment]
MQTT comunincations are managed by the library PubSubClient version 2.8 (never changed)
Have you built the project by your own using a different library version?
Have you tried the pre-build version?

**Comment by shogunxam** [comment]
Sorry, I replied directly to your email and missed your edit.
The strings sent, for memory management reasons, have a fixed length, the string composed by Location/Gateway cannot be longer than 49 characters

**Comment by l33tn00b** [comment]
That's why the shorter string fixed it. Got it working, so the issue may be closed.
